.github/workflows/deploy-to-paas.yml
manifest.yml

Spreadsheet ID added to test environment secrets in GitHub
Ranges added to manifest.yml (the space is intentional as that's what's on the spreadsheet)
Secret used in cf push command in deploy-to-paas.yml

BAU-150 Enable test spreadsheet for request access to private beta form

---

.github/workflows/deploy-to-paas.yml

Spreadsheet ID added to test environment secrets in GitHub
Ranges added to manifest.yml (the space is intentional as that's what's on the spreadsheet)
Secret used in cf push command in deploy-to-paas.yml

DFA-150 Enable test spreadsheet for request access to private beta form

---

.github/workflows/deploy-to-paas.yml
manifest.yml

The `--var` flag sets values for variable substitution in the manifest file. The vars from GitHub need to be piped through to the deployment environment.

DFA-304: Set secret env vars correctly

---

src/views/contact-us.njk

If the validation fails, the value of the how-can-we-help textarea is not rendered in the template.  The text for the submit button was is also wrong.
Render value of how-can-we-help textarea when validation fails.
Alter text of submit button.

DFA-28 The mystery of the missing text

---

manifest.yml

Somebody didn't like the space that was at the end of sheet name so it's not working now.  In fairness, I should have seen this coming ...
Remove spaces from the end of the sheet name in both ranges

DFA-150 get the spreadsheet working

---

src/views/find-out-more.njk
src/views/getting-started.njk
src/views/identity-checks.njk
src/views/register-confirm.njk

Update the places where we refer to 'registering your interest' to set clearer expectations about what will actually happen if you do it. 
Some service teams were expecting quite different things from our register interest/first contact process, so we needed to clear it up. In particular, we needed to make it less about joining beta, and more about speaking to us and staying up to date.

Update 'register your interest' content on 4 pages 

---

.github/workflows/deploy-to-paas.yml

TIL PaaS will need values for things you put in the manifest.  Which should have been obvious to me really.

DFA-45 Add empty values for vars

---

.github/workflows/build.yml
.github/workflows/deploy.yml
.github/workflows/test-pr.yml
.gitignore
manifest.yml
package.json

Add a "Test PR" workflow that deploys a preview app each time a pull request is opened or updated.
The workflow uses reusable workflows which will be later used in the production pipeline as well.
The preview pipeline builds the app, runs unit tests, deploys to PaaS and runs acceptance tests (stub job for now).
Each app is deployed on a unique URL derived from the branch name.
- Cache npm modules
- Run unit tests using mocha

DFA-376: Deploy a preview app for each pull request

---

.github/workflows/build.yml
.github/workflows/check-pr.yml
.github/workflows/deploy-to-paas.yml
.github/workflows/deploy.yml
.github/workflows/run-acceptance-tests.yml
.github/workflows/run-unit-tests.yml
.github/workflows/test-pr.yml
manifest.yml

**Complete the production pipeline**
Update the Deploy pipeline to use the shared workflows and deploy to the production environment if all tests have passed.
Both the build job and the unit tests must succeed for the deployment to the 'test' environment to go ahead. Deploy to the the production environment if acceptance tests have passed in 'test'.
Use lowercase for names of GHA inputs and secrets.
**Rename workflows for greater clarity**
Swap contents of deploy.yml and deploy-to-paas.yml
**Add reusable workflows for unit and acceptance tests**
**Handle empty config values**
Some config values are not present in non-prod environments yet `cf push` requires all env vars in the manifest file to be preset when deploying. Fix this by using env vars for the optional vars and use shell …

DFA-376 & DFA-377: Workflow housekeeping & production pipeline

---

src/views/contact-us.njk

Enable go back link to redirect to previous page on contact us page

Enable go back link to redirect to previous page on contact us page

---

.github/workflows/clean-up-pr.yml

Add an action to delete the preview deployment associated with a PR when the PR is merged or closed.

DFA-376: Clean up PR preview

---

.github/workflows/check-pr.yml

PaaS imposes a limit of 63 characters for the host part of the app's URL.
The host name is constructed from the fixed prefix plus the branch name.
Use a shorter prefix to allow for longer branch names.

DFA-376: Allow longer branch names in PR previews

---

.github/workflows/check-pr.yml
.github/workflows/delete-deployment.yml
.github/workflows/deploy-branch.yml
.github/workflows/deploy-to-paas.yml
.github/workflows/publish.yml

PaaS requires URLs to be all lower case and the hostname portion can't exceed 63 characters. This means we have to transform the {prefix-branch_name} hostname before deploying.
The URL is constructed from the app name, when passed in, on the "Deploy to PaaS" workflow call.
Fix the script to manually depete a deployment - it now uses the correct branch name.
Add a script to clean up old deployments on schedule.

DFA-376: Validate preview deployment URL & clean up old deployments

---

src/app.ts

Update URLs used so members of the public go to the signin.account.gov.uk contact form and government services go to our contact form.

DFA-476 Update URLs in support page

---

.github/workflows/check-pr.yml
.github/workflows/publish.yml
.github/workflows/run-acceptance-tests.yml
.gitignore
features/support/test-setup.ts
package-lock.json
package.json
tsconfig.json

**Add configuration to run acceptance tests in the deployment pipeline**
- Add npm script to run acceptance tests
- Amend the acceptance tests workflow to run the cucumber script
- Add a test setup script to manage browser launching and closing, set host URL and add functionality to the test context
- Configure ts compiler to ignore the test files
- Use the URL class to construct URLs and avoid invalid URLs that may contain double forward slashes when the test host is set manually
- Use the updated acceptance tests workflow to run the cucumber tests when deploying a PR preview pr publishing the app.
- Use the deployment URL provided by the Deploy to PaaS workflow to run the tests.

DFA-377: Run acceptance tests in the deployment pipelines

---

.github/workflows/publish.yml

This is needed to make Zendesk integration work

DFA-348: Pull through the Zendesk group ID to the prod deployment

---

.github/workflows/publish.yml

We have now gone live and will be using the public URL from now on to refer to production.

DFA-348: Update production deployment URL

---

features/contact-us.feature
features/request-private-beta.feature
features/support/steps/shared-steps.ts
features/support/steps/support-steps.ts
tsconfig.json

Add a step to check the content of the success page for forms that post to Zendesk or Sheets.
We still need a feature file for the register pages but we're waiting for the ACs.
Comment out `rootDir` in `tsconfig.json`; typescript can still find what it needs but IntelliJ no longer gets upset when you include the shared functions in a step.

BAU Add steps for Zendesk and Sheets forms

---

src/views/contact-us-details.njk
src/views/contact-us.njk

The back links on contact-us and contact-us-details weren't working (one used JavaScript from a time when we didn't know where back was going to be).

BAU Fix back links

---

features/base-template.feature
features/decide.feature
features/support/steps/decide-steps.ts
src/views/base-evaluate.njk
src/views/base.njk
src/views/decide-design-patterns.njk
src/views/decide-private-beta.njk
src/views/decide-timescales.njk
src/views/decide-user-journeys.njk
src/views/decide.njk

We've recently set up a "proper" url rather than a default url provided by PaaS.

BAU: Update link to technical documentation

---

features/decide-contact-links.feature
features/support/steps/decide-contact-links-steps.ts
src/app.ts
src/views/contact-us-details.njk
src/views/decide-design-patterns.njk
src/views/decide-user-journeys.njk
src/views/decide.njk
src/views/request-submitted.njk
src/views/there-is-a-problem.njk

Add a view `there-is-a-problem.njk` to display when an unhandled error is thrown.
Add the `app.use` gubbins so that the page is displayed when an unhandled error is thrown.

DFA-558 Generic error page

---

src/app.ts
src/controllers/contact-us.ts
src/controllers/decide.ts
src/controllers/register.ts
src/lib/sheets/stubSheets/stubSheetsService.ts
src/lib/validation/validation.spec.ts
src/lib/validation/validation.ts
valid-email-domains.txt

The code which validates forms loads a file full of email addresses.  This was originally a quick fix to add the functionality as soon as possible.  This PR fixes the quick fix and only loads the file at app initialisation instead of every time a form is submitted.
* Change Validation class to provide a singleton type method for getting a single instance of the class. Pass form being validated and required fields in as arguments to the validation method instead of as arguments to a constructor.
* Load valid email domains synchronously
* Put all valid emails into a file - do not hardcode any
* Terminate execution if the file does not load
* Set the instance as a property of the app
* Use that app property in the controller methods that deal with form submissions.
* Update tests to use the …

DFA-528 Only load form validator once

---

monitoring/template.yaml

Alerts currently go to `di-dfa-tech-notifications` but should go to `di-dfa-alerts`.
Change `SLACK_CHANNEL` in the canaries template to have the value 'di-dfa-alerts`.
Once merged, this should run SAM which will update the lambda to use the new channel.

BAU Change alerting channel

---

features/contact-us.feature
src/views/contact-us.njk

We need to remove the line. that links to the Verify status page, because this is really confusing. We were meant to have a new one, but it's taking a while so we should remove this in the meantime.

Remove status page link

---

src/views/getting-started-private-beta.njk

This is to make the link text reflect the new wording on the sign up form - it's now 'sign up to get access' instead of 'register your interest'.

Update link text on private beta page

---

ci/github-actions-aws-oidc-provider-template.yml

Canaries deployment fails because of a missing `lambda:ListTags` permission. Add this permission and see what else is missing when it fails again.

BAU Update OIDC policy

---

features/support/steps/base-template-steps.ts
features/support/steps/contact-us-steps.ts
features/support/steps/decide-contact-links-steps.ts
features/support/steps/documentation-steps.ts
features/support/steps/mailing-list-steps.ts
features/support/steps/register-steps.ts
features/support/steps/request-private-beta-steps.ts
features/support/steps/shared-functions.ts
features/support/steps/shared-steps.ts
features/support/steps/support-steps.ts
features/support/steps/user-journeys-steps.ts
features/support/test-setup.ts

- Correctly construct URLs in feature tests 
Avoid failing tests due to double slashes caused by directly adding two strings. Use the URL class instead to handle URL construction.
---
_Formatting changes in a separate commit_
- Apply formatting
- Optimise imports
- Use one kind of quotes for strings (single quotes)
- Remove duplicated code fragments by moving the repeated blocks into functions.

BAU: Bug fixes and formatting in feature tests

---

assets/javascripts/application.js
assets/javascripts/back-to-top.js
assets/javascripts/cookies.js
nodemon.json
package-lock.json
package.json
src/controllers/mailing-list.ts
src/lib/zendesk/ZendeskService.ts
src/lib/zendesk/interface.ts
src/lib/zendesk/stubZendesk/stubZendeskService.ts
src/views/base-evaluate.njk
src/views/base.njk
src/views/documentation-design-recommendations.njk
tsconfig.json

- Enable the noUnusedLocals flag in tsconfig.json 
Remove unused locals to let the build succeed
- Move dotenv to devDependencies
-  Only load the back-top-script when it's needed
-  Only initialise the Google Tag Manager if the tag value is provided 
- Add nodemon config to allow it to automatically restart the app for local development

BAU: Enable `noUnusedLocals` and optimise JavaScripts

---

assets/css/app.scss
src/controllers/mailing-list.ts
src/views/accessibility.njk
src/views/base-side-nav.njk
src/views/base.njk
src/views/contact-us-details.njk
src/views/cookies.njk
src/views/documentation-design-recommendations.njk
src/views/documentation-user-journeys.njk
src/views/documentation.njk
src/views/features.njk
src/views/getting-started-private-beta.njk
src/views/getting-started.njk
src/views/index.njk
src/views/macros/breadcrumbs.njk
src/views/mailing-list-confirmation.njk
src/views/mailing-list.njk
src/views/privacy-policy.njk
src/views/register-confirm.njk
src/views/register-error.njk
src/views/register.njk
src/views/request.njk
src/views/roadmap.njk
src/views/support.njk

**Add a macro to generate breadcrumbs** 
Generate breadcrumbs programmatically by specifying the intermediate crumbs and current page name in the templates.
Use the page title if the current page name is not provided.
Add breadcrumbs placeholder to the `base.njk` template.
---
-  Add placeholder for back link to base.njk
-  Set consistent classes on all views 
Make the top and bottom spacing consistent on all views and the same as on the self-service pages.

BAU: Use macros and govuk components

---

assets/css/app.scss
features/request-private-beta.feature
features/support/steps/base-template-steps.ts
features/support/steps/documentation-steps.ts
features/support/steps/shared-functions.ts
features/support/steps/shared-steps.ts
features/support/steps/user-journeys-steps.ts
package-lock.json
package.json
src/views/404.njk
src/views/base.njk
src/views/common/cookie-banner.njk
src/views/contact-us-confirm.njk
src/views/contact-us.njk
src/views/cookies.njk
src/views/documentation-design-recommendations.njk
src/views/getting-started-private-beta.njk
src/views/index.njk
src/views/macros/table.njk
src/views/mailing-list-confirmation.njk
src/views/mailing-list.njk
src/views/register-confirm.njk
src/views/register.njk
src/views/request-error.njk
src/views/request-submitted.njk
src/views/request.njk

- Upgrade to the latest version of the GOV.UK Design System 
See release notes for 4.0.0: https://github.com/alphagov/govuk-frontend/releases/tag/v4.0.0
- Use standard spacing on all views as per the GOV.UK Design System 
Let the design system handle the layout (https://design-system.service.gov.uk/styles/layout/)
- Use govuk components
-  Use the `govukButton` component instead of the `<button>` tag where possible
- Use govuk components in forms: `govukInput`, `govukRadios` and `govukTextarea`
-  Use the `govukCookieBanner` component instead of HTML
-  Use the `govukPanel` and `govukNotificationBanner` components
- Add a macro to generate a table 
Programmatically generate tables using the macro and the `govukTable` component

BAU: Upgrade to the latest version of the GOV.UK Design System 

---

features/register.feature
features/support.feature
features/support/steps/shared-steps.ts
src/controllers/contact-us.ts
src/controllers/decide.ts
src/controllers/mailing-list.ts
src/controllers/register.ts
src/controllers/support.ts
src/lib/validation/validation.ts
src/routes/mailing-list.ts
src/views/base-form.njk
src/views/contact-us.njk
src/views/macros/error-summary.njk
src/views/macros/form-inputs.njk
src/views/macros/form.njk
src/views/mailing-list.njk
src/views/register.njk
src/views/request.njk
src/views/support.njk

- Add a base template for views that need to display forms 
The template automatically generates the form and error summary if errors are present.
This fixes the "Incorrectly Labelled Form Fields" issue as incorrect labels were assigned due to bad a copy/paste process.
The forms now automatically generate correct hrefs for fields with errors.
- Make macros for reusable form inputs 
Generate form inputs using the macros
- Add a macro to generate a form

DFA-2085: Add macros and layout for forms

---

features/support/steps/base-template-steps.ts
features/support/steps/contact-us-steps.ts
features/support/steps/decide-contact-links-steps.ts
features/support/steps/documentation-steps.ts
features/support/steps/mailing-list-steps.ts
features/support/steps/register-steps.ts
features/support/steps/request-private-beta-steps.ts
features/support/steps/shared-functions.ts
features/support/steps/shared-steps.ts
features/support/steps/support-steps.ts
features/support/steps/user-journeys-steps.ts
features/support/test-setup.ts
src/config/configureViews.ts
src/controllers/register.ts
src/controllers/support.ts
src/lib/validation/email-validator/index.ts
src/lib/validation/validation.spec.ts
src/lib/validation/validation.ts
src/views/macros/form.njk
src/views/register.njk
src/views/support.njk
tsconfig.json

-  Point the error link to the first radio button when no option selected
-  Format steps 
Apply prettier/eslint formatting
- Fix bug in email validator
Check that the whole part after the @ sign in the email matches one of the domains to make sure domains that end in a valid domain but prefixed with an arbitrary string are rejected. This means that domains such as `foo.gov.uk` are now rejected where they were previously accepted.

DFA-2085: Point to the first radio button on error

---

valid-email-domains.txt

add `digital.justice.gov.uk` to list of allowed domains.
eventually change implementation to work like SSE.

BAU add allowed domain

---

src/views/accessibility.njk

Recently, we introduce the GOV.UK One Login status page (https://status.account.gov.uk/) to communicate incidents to external stakeholders. There are several accessibility issues on the status page, so of which can only be fixed by the 3rd party provider of some of the functionality of the status page (statuspage.io) 
This means, the accessibility statement has to be updated to list the non-compliance of the GOV.UK One Login status page. 
Content review was done here: https://docs.google.com/document/d/1BR3VPvjXgKC5ipmWIVV537ekR1RFlVKnV2fsO6_PRso/edit#

Updated the accessibility statement due to new status page

---

src/views/accessibility.njk

Earlier in the year, we found several accessibility issues with the One Login status page. Since then, the majority of these issues have now been fixed. Therefore, we want to update the accessibility statement to take off the bullet points of issues that are now resolved. 
The updated statement (2i'ed by Kim Clayden on 9 June 2023) can be found here: https://docs.google.com/document/d/1u6C4d2MrKemiAoz3-XcKS6XffijO63iHGWgldyfZa9A/edit

Removed bullet points of accessibility issues that have now been fixed

---

resources/allowed-email-domains.txt

Add digital.mod.uk and digital.trade.gov.uk domains to accepted government services emails

SSE-2789 - Add digital.mod.uk and digital.trade.gov.uk domains to accepted government services emails

---

.github/workflows/publish-dev.yml
.github/workflows/upload-frontend.yml
Dockerfile
infrastructure/frontend/frontend.template.yml

-  Updated GitHub env vars for development pipeline
- Trigger dev pipeline on push to main
- create publish to dev workflow
- [upload-frontend.yml](https://github.com/govuk-one-login/onboarding-product-page/blob/SSE-2987-deploy-workflow/.github/workflows/upload-frontend.yml)
- [publish-dev.yml](https://github.com/govuk-one-login/onboarding-product-page/blob/SSE-2987-deploy-workflow/.github/workflows/publish-dev.yml)
- [Dockerfile](https://github.com/govuk-one-login/onboarding-product-page/blob/SSE-2987-deploy-workflow/Dockerfile)
- [frontend.template.yml](https://github.com/govuk-one-login/onboarding-product-page/blob/SSE-2987-deploy-workflow/infrastructure/frontend/frontend.template.yml)
- secure pipelines for Product pages (PaaS removal)
- workflow to support the moving of Product Pages …

SSE-2987 product pages deployment workflow

---

.dockerignore
Dockerfile
Dockerfile-dev
infrastructure/frontend/frontend.template.yml

Sub-Task for [SSE-3095](https://govukverify.atlassian.net/browse/SSE-3095).
The Flag readonlyRootFilesystem in the Product Pages Template Definition File is currently set to False which is causing a High Severity Record to be reported in Security Hub - This should be set as per the instructions in [Amazon ECS controls - AWS Security Hub](https://docs.aws.amazon.com/securityhub/latest/userguide/ecs-controls.html) (ECS.5).
This issue was also highlighted for Admin Portal but a ticket had been raised previously and the issue has been fixed in that system.
The docker file runs `npm run local` as a startup command, but should run `npm start`. Any install or build commands should run while the image is being built, not as CMD.
[SSE-3095]: …

SSE-3170: Turned on ECS Container ReadonlyFilesystem

---

resources/allowed-email-domains.txt

Add digital.hmrc.gov.uk domain to allowed email domains list

SSE-3196 Add digital.hmrc.gov.uk domain to allowed email domains list

---

infrastructure/frontend/frontend.template.yml

- set AWSManagedRulesAnonymousIpList rule action to count
- Deploy the WAF policies in COUNT mode
- No traffic should be blocked by the WAF
- https://govukverify.atlassian.net/browse/INCIDEN-700

SSE-3238 - Set WAF rule action to count

---

package-lock.json
package.json

- N/A
- Bumps express to version 4.19.2, as older versions of express have a vulnerability when using `res.redirect()`
https://github.com/advisories/GHSA-rv95-896h-c2vc
- N/A

BAU: bumps express to v 4.19.2

---

.github/workflows/deploy-dev.yml
.github/workflows/deploy-prod.yml

In the merge queue we try to deploy to dev. Without concurrency protection on the deployment, it's only safe to run one set of checks at a time, which is slow. For production, concurrent deployments will succeed in AWS, but show as failed in github

BAU: Prevent concurrent deploys to the same environment

---

src/views/documentation-let-users-navigate.njk

Update design recommendation guidance for using the One Login Header component. This is in response to the new Design System service navigation component being launched as part of v5.6.0.
JIRA: https://govukverify.atlassian.net/browse/OLH-2209
> [!WARNING]
`git fetch --all && git rebase …

OLH-2209: Update documentation-let-users-navigate.njk

---

package-lock.json
package.json
src/lib/sheets/realSheets/realSheetsService.ts

> [!WARNING]
Tested locally and on the dev env - works as expected, rows appended to the first blank row below existing form submission data.
-   all methods signatures and …

ATO-998: Bump @googleapis/sheets from 0.3.0 to 9.4.0

---

package-lock.json
package.json

- Bumps axios to version 1.82
- Ran `npm audit fix` to bump Bump babel dependency due to: https://github.com/advisories/GHSA-968p-4wvh-cqc8
-   [ ] tests have been written to cover any new or updated functionality
-   [ ] new configuration parameters have been deployed to all environments, see [configuration management](https://govukverify.atlassian.net/l/cp/N7q3Vh3r).
-   [ ] all external infrastructure dependencies have been updated in all …

BAU: bump axios
