- package-lock.json
- package.json
- src/app.ts
- src/email-validator/index.ts
- src/validation/index.ts
- src/validation/validation.ts
- src/views/register.njk
Port registration form from FreeMarker to Nunjucks
Port validation from Java to TypeScript
I'm not in love with the layout or structure of this and the validation stuff could definitely do with a re-factoring but hey, it works and it will make more sense to refactor when we have a new form.
Next job - do the Sheets stuff with our definitely valid data. And some tests probably.  That would be a good idea.
> DFA-312 Registration Form

- assets/css/app.scss
- assets/javascripts/cookies.js
- package-lock.json
- package.json
- src/app.ts
- src/views/accessibility.njk
- src/views/base.njk
- src/views/cookies.njk
- src/views/find-out-more.njk
- src/views/getting-started.njk
- src/views/identity-checks.njk
- src/views/index.njk
- src/views/privacy-policy.njk
- src/views/register-confirm.njk
- src/views/register-error.njk
- src/views/register.njk
Main .njk template adjusted so header and footer are reusable
Added html pages
> Adjust main template add html pages

- .env.example
- src/app.ts
- src/sheets/SheetsService.ts
- src/sheets/interface.ts
- src/sheets/realSheets/realSheetsService.ts
- src/sheets/stubSheets/stubSheetsService.ts
- src/validation/validation.spec.ts
- src/validation/validation.ts
- src/views/base.njk
- src/views/register.njk
- src/views/request.njk
Refactor validation to have checked values passed in.
Refactor Sheets to take a data Range for destination data.
Create `request.njk` view to render new form.
Add new routes for new view with necessary values passed in.
Add extra env vars to `.env.example`
Add a slash to the css link in the base template.
Points to the success and failure pages for "Register" and these should be updated when the other pages become available.
> Request Private Beta Form

- assets/css/app.scss
- src/app.ts
- src/views/base-evaluate.njk
- src/views/decide.njk
Create decide page, add left side navigation, create decide base template
> Create decide page, add left side navigation

- .env.example
- src/app.ts
The request beta form will save to a different spreadsheet so add some config.
> DFA-150: Add a different spreadsheet id value

- src/views/base-evaluate.njk
- src/views/request.njk
Remove breadcrumbs.
Replace with back link that points to `/decide/private-beta`
> BAU Fix navigation on Request access to private beta form

- assets/css/app.scss
- src/app.ts
- src/views/decide-timescales.njk
- src/views/decide.njk
Create page for evaluate stage Timescales
> Create page for evaluate stage Timescales

- src/views/decide.njk
Update H1 and contact headers size
> Update H1 and contact headers size

- .env.example
- src/app.ts
- src/validation/validation.ts
- src/views/contact-us.njk
- src/views/register.njk
- src/zendesk/ZendeskService.ts
- src/zendesk/index.ts
- src/zendesk/interface.ts
- src/zendesk/realZendesk/realZendeskService.ts
- src/zendesk/stubZendesk/stubZendeskService.ts
Create form and do validation.
Add routes.
Fix problem in `register.njk` from missing tag.
The back link doesn't go anywhere right now - we'll have to figure out where to get that from.  Maybe the referrer if we can get that from the request.
This includes a rebase from DFA-151_request_success_page because that included some stuff this needs.
> DFA-28 contact us form

- src/app.ts
- src/views/request-submitted.njk
This adds the content as shown in the ticket.
> DFA-151 Request submitted page

- src/app.ts
- src/views/decide-user-journeys.njk
Create User Journeys page for evaluate stage
> Create User Journeys page for evaluate stage

- src/app.ts
- src/views/decide-design-patterns.njk
> Create Design Patterns page

- .github/workflows/deploy-to-paas.yml
- manifest.yml
> DFA-150: Enable request private beta test sheet

- src/app.ts
- src/sheets/realSheets/realSheetsService.ts
Add debug message and  move success message.
> DFA 150 enable request private beta test sheet

- src/views/request.njk
DFA-150: Add error border to inputs when error state
> DFA-150: Add error border to inputs when error state

- .github/workflows/deploy-to-paas.yml
Add trailing backslashes so new variables are parsed
> DFA-45 Add backslashes

- manifest.yml
The Zendesk tag env var was missing.
Add ZENDESK_TAG and value
> Add missing env var

- src/app.ts
- src/views/decide-private-beta.njk
Create Find out more about privare beta page
> DFA-150: Create Find out more about privare beta page

- src/views/decide-private-beta.njk
> Content update

- src/views/base.njk
Implement support link in the top main menu
> Implement support link in the top main menu

- src/app.ts
- src/views/contact-us-details.njk
Create contact us page for service teams
> Create contact us page for service teams

- src/views/contact-us-confirm.njk
Create confrimation contact us page
> Create confrimation contact us page

- src/app.ts
- src/views/support.njk
Support page for rising queries
> Support page for rising queries

- src/views/find-out-more.njk
- src/views/getting-started.njk
Markup update for Find out more and Get started pages
> Markup update for Find out more and Get started pages

- src/views/contact-us-confirm.njk
> BAU Add full-stop

- assets/css/app.scss
Update width and margines on breakpoints for navigation
> Update width and margines on breakpoints for navigation

- src/app.ts
- src/validation/validation.spec.ts
- src/views/base-evaluate.njk
- src/views/base.njk
- src/views/index.njk
- src/views/request.njk
Content and html markup update
Update assets routing to fix not found assets error on the decide stage pages
> Update error message, move error block above H1 on request to join form

- src/views/decide.njk
- src/views/request-submitted.njk
> Fixed paths in links

- .env.example
- src/app.ts
- src/validation/validation.spec.ts
- src/validation/validation.ts
- src/views/register.njk
Remove unused fields.
Move error messages to top of page.
Change content.
Highlight errored inputs in red.
Remove conditional validation from validation.
Update tests.
Unrelated: remove stub S3 setting from .env.example
> DFA-363 Amend registration form

- src/views/decide-timescales.njk
Content update for timescales page
> Content update for timescales page

- .github/workflows/delete-deployment.yml
- Format the dates in the canonical yyyy-mm-dd format so the date comparison works correctly
- Handle the case when the last upload date is missing
- Add some logging for easier debugging
> DFA-376: Fix logic to clean up stale deployments

- src/views/base.njk
Remove extra `<ul>` that was stopping the menu from working.
> BAU Fix menu

- .github/workflows/publish.yml
With the values from blackbox in GitHub it should just be a question enabling the proper implementation of Zendesk.  This assumes that the value of zendesk_tag in manifest.yml is sufficient.
> DFA-45 Switch on Zendesk

- .github/workflows/publish.yml
- src/zendesk/ZendeskService.ts
- src/zendesk/interface.ts
- src/zendesk/realZendesk/realZendeskService.ts
- src/zendesk/stubZendesk/stubZendeskService.ts
Pull through Zendesk secrets to prod environment
Update contact-us form handling to use Map<String, String> in line with new validator.
> DFA-45 New PR to fix Zendesk

- src/app.ts
Don't render that, render this
> BAU Fix what's rendered for a successful form submission

- features/base-template.feature
- features/support/steps/base-template-steps.ts
Start a collection of scenarios for the base template, initially focusing on the menu button displayed at 640px or less.
> BAU Add acceptance tests for base template

- src/views/getting-started.njk
Updating the content on the Get started page. 
To reflect the fact that the evaluate stage will change the 'get started' process a bit, and to update some out of date information.
> [DO NOT MERGE UNTIL EVALUATE STAGE IS LIVE] DFA-322 Update get started content 

- manifest.yml
Change value for zendesk tag to `sign_in_service_teams`
> BAU Change Zendesk tag

- src/controllers/decide.ts
- src/routes/decide.ts
- src/routes/register.ts
- src/views/request-error.njk
Add view for errors with request access to private beta forms.  Add method to controller and route.  Also update route for register as register-error wasn't included.
> DFA-369 Request access to private beta form error

- src/views/404.njk
- src/views/accessibility.njk
- src/views/contact-us-confirm.njk
- src/views/contact-us-details.njk
- src/views/contact-us.njk
- src/views/cookies.njk
- src/views/decide-design-patterns.njk
- src/views/decide-private-beta.njk
- src/views/decide-timescales.njk
- src/views/decide-user-journeys.njk
- src/views/decide.njk
- src/views/features.njk
- src/views/getting-started.njk
- src/views/index.njk
- src/views/privacy-policy.njk
- src/views/register-confirm.njk
- src/views/register-error.njk
- src/views/register.njk
- src/views/request-error.njk
- src/views/request-submitted.njk
- src/views/request.njk
- src/views/roadmap.njk
- src/views/support.njk
- src/views/there-is-a-problem.njk
Updated the content to give more information about what to expect from joining the private beta.
> DFA-623 private beta content

- monitoring/lambdas/sns_to_slack/package-lock.json
- package-lock.json
Update `nanoid` to 3.3.1
Update `minimist` to 1.2.6
> BAU Update packages

- assets/css/app.scss
- src/views/base-evaluate.njk
- src/views/base.njk
- src/views/index.njk
Add beta phase banner to layout
> DFA-1442 Add beta phase banner to layout

- .github/workflows/delete-deployment.yml
- .github/workflows/deploy-smoke-tests.yml
- .github/workflows/deploy-to-paas.yml
- assets/javascripts/application.js
- assets/javascripts/back-to-top.js
- assets/javascripts/cookies.js
- features/base-template.feature
- features/documentation-contact-links.feature
- features/documentation.feature
- features/left-hand-navigation-menu.feature
- features/register.feature
- Use latest actions
-  Apply formatting to feature tests and JS assets
> BAU: Use latest actions to fix deployment to PaaS

- src/views/roadmap.njk
Added divider lines above the "Identity checks will be added in future" and "Updates" h2s.
> Add divider lines to sections on the 'Roadmap' page of the product site

- src/views/roadmap.njk
Updating the content on the roadmap to add more updates, and to clarify which workstream they relate to. 
Our product offer is expanding and we're onboarding services to identity.
> DFA-2246-Roadmap update 

- src/routes/site.ts
- src/views/service-unavailable.njk
Build 'service unavailable' page frontend
> SSE-2376 - Build 'service unavailable' page

- src/views/roadmap.njk
Forgot to do this when I moved the 'service dashboard' into 'recently released' section
> Update last updated date

- package-lock.json
- package.json
SSE-2486-Upgrade to govuk-frontend v4.5.0
> SSE-2486-Upgrade to govuk-frontend v4.5.0

- .github/workflows/check-code-quality.yml
- .github/workflows/check-pr.yml
- .github/workflows/clean-up-deployments.yml
- .github/workflows/delete-deployment.yml
- .github/workflows/deploy-branch.yml
- .github/workflows/deploy-smoke-tests.yml
- .github/workflows/deploy-to-paas.yml
- .github/workflows/publish.yml
- .github/workflows/run-acceptance-tests.yml
- Use the latest DI actions
- Add vulnerabilities check for PRs
- Set concurrency per environment
Avoid deployments to different environments blocking each other
- Split the delete deployment workflow into two
Keep the cleanup functionality in a separate workflow so it can be set to send notifications separately
> BAU: Use the latest DI actions

- src/views/contact-us.njk
- src/views/mailing-list.njk
- src/views/register.njk
> SSE-2579 Update form lables

- assets/css/app.scss
- src/views/index.njk
Update live homepage tags and content under specific headers
> SSE-2645 - Update live homepage tags and content under specific headers

- .github/workflows/check-pr.yml
- .github/workflows/deploy-branch.yml
- .github/workflows/deploy-to-paas.yml
- .github/workflows/publish.yml
- assets/css/app.scss
- manifest.yml
- src/app.ts
- src/views/base.njk
Implement a banner for non-production environments
> SSE-2595 Implement a banner for non-production environments

- src/views/base.njk
> SSE-2594 - Footer update

- src/views/roadmap.njk
Update the product roadmap page
> SSE-2662 - Update the product roadmap page - May 2023

- src/views/about/checking-users-identities.njk
Update content for identity section
> Update content for identity section

- src/views/documentation-user-journeys.njk
Update 'User journey maps' page
> SSE-2706 Update 'User journey maps' page

- src/views/roadmap.njk
> SSE-2717 Update Roadmap page

- features/left-hand-navigation-menu.feature
- src/views/documentation-design-recommendations.njk
- src/views/side-nav/documentation-side-nav.njk
Update 'Design recommnedations' page
> SSE-2708 - Update 'Design recommnedations' page

- features/documentation-contact-links.feature
- src/views/documentation-change-credentials.njk
Update 'Show users where to change their GOV.UK One Login credentials' page
> SSE-2709 - Update 'Show users where to change their GOV.UK One Login credentials' page

- src/views/documentation-let-users-navigate.njk
Content changes to header guidance for sign out functionality
> SSE-2747 - content changes to header guidance for sign out functionality

- src/views/roadmap.njk
> SSE-2768 - Roadmap update

- src/app.ts
Add in the middleware code in the headers to implement http access control
> Add in access control headers in the app

- package-lock.json
- package.json
- src/app.ts
- src/config/helmet.ts
SSE-2796 - Implement OWASP recommended HTTP response headers using a helmet configuration file.
> SSE-2796 - Implement OWASP recommended HTTP response headers

- src/views/about/checking-users-identities.njk
Update content for user identities
> SSE-2842 - Update content for user identities

- .env.example
- manifest.yml
- package-lock.json
- src/controllers/contact-us.ts
- src/lib/zendesk/realZendesk/realZendeskService.ts
Add extra parameters and functionality for contact us form to be able to separate Zendesk tickets for One Login Admin Tool
> SSE-2828 - Add extra parameters and functionality for contact us form

- package-lock.json
- resources/allowed-email-domains.txt
Add digital.homeoffice.gov.uk to allowed register interest domain list
> SSE-2882 - Add digital.homeoffice.gov.uk to allowed register interest domain list

- src/views/roadmap.njk
> SSE-2897 Roadmap update

- assets/css/app.scss
- assets/css/modules/_header.scss
- package-lock.json
- src/routes/site.ts
- src/views/about/checking-users-identities.njk
- src/views/about/evidence-types.njk
- src/views/about/signing-users-in.njk
- src/views/accessibility.njk
- src/views/base.njk
- src/views/cookies.njk
- src/views/documentation-let-users-navigate.njk
- src/views/documentation-user-journeys.njk
- src/views/documentation.njk
- src/views/getting-started.njk
- src/views/index.njk
- src/views/privacy-policy.njk
- src/views/roadmap.njk
- src/views/side-nav/about-side-nav.njk
Changes to go live with Admin Tool launch, content updated, style updates, markup updates
> SSE-2143 - Changes to go live with Admin Tool launch

- src/views/base.njk
Add 'About' Link to Footer of Product Pages
> SSE-2856 Add 'About' Link to Footer of Product Pages

- infrastructure/frontend/frontend.template.yml
-  product pages deployment domain
- deploy product pages in AWS
> SSE-2987 add DNS record for product pages

- src/views/roadmap.njk
Update Roadmap page to reflect recent Admin Tool release
> SSE-3015 - Update Roadmap page to reflect recent Admin Tool release

- ci/aws-accounts.json
- ci/aws.sh
- ci/configure-deployment-parameters.sh
- infrastructure/frontend/frontend.template.yml
- add env var as in paas 
- add script to add application env and secret
- add `aws-accounts.json` for AWS accounts
- add` aws.sh` script
- `SSE-3013 `- migrate paas Env vars on the new AWS
> SSE-3013 add env vars in ecs

- .github/workflows/deploy-component.yml
- .github/workflows/publish-prod.yml
-  add Workflow for deployment to build env
- updated preview workflow
- SSE-2991
> Sse 2991 release workflow

- src/views/privacy-policy.njk
SSE-3035 - Privacy policy update
> SSE-3035 - Privacy policy update

- .github/workflows/check-code-quality.yml
- .github/workflows/check-pr.yml
- .github/workflows/deploy-component.yml
- .github/workflows/run-acceptance-tests.yml
- .github/workflows/run-unit-tests.yml
- infrastructure/frontend/frontend.template.yml
- deploy workflow on PR and run acceptance tests
- check pr workflow
> check PR workflow

- .github/workflows/clean-up-deployment.yml
- .github/workflows/deploy-branch.yml
Deletion of stack on cron basis
> Clean-up-deployment

- src/views/documentation-user-journeys.njk
Remove content from  user journeys page
> SSE-3046 - Remove content from  user journeys page

- package-lock.json
- src/lib/sheets/realSheets/realSheetsService.ts
Remove unused logging for google api implementation
> SSE-3087 remove logging for google api implementation

- .env.example
- ci/configure-deployment-parameters.sh
- infrastructure/frontend/frontend.template.yml
- manifest.yml
Added new Secrets and Parameters to support ServiceNow Integration.
> SSE-3132:Created Environment Variables for ServiceNow Parameters and Secrets

- .env.example
- @types/oauth2.d.ts
- @types/serivcenowcredentials.d.ts
- README.md
- src/controllers/contact-us.ts
- src/lib/oauth2Token.ts
- src/lib/servicenow/ServicenowService.ts
- src/lib/servicenow/index.ts
- src/lib/servicenow/interface.ts
- src/lib/servicenow/realServicenow/realServicenowService.ts
- src/lib/servicenow/stubServicenow/stubServicenowService.ts
> SSE-3130 - Implement ServiceNow endpoint

- .github/workflows/build-frontend-image.yml
- .github/workflows/publish-dev.yml
- .github/workflows/publish-prod.yml
- .github/workflows/upload-frontend.yml
- Dockerfile-dev
- infrastructure/frontend/frontend.template.yml
- package.json
- updated frontend template - added dynatarce secrets
- updated GHA for image upload
- updated publish workflow
- updated Dockerfile
- added dev Dockerfile
- Dynatrace integration for frontend
- SSE-3113
> SSE-3113 Product Pages Dynatrace Integration

- resources/allowed-email-domains.txt
Add levellingup.gov.uk domain to allowed list
> SSE-3184 Add levellingup.gov.uk domain to allowed list

- resources/allowed-email-domains.txt
Add domains to allowed email list
> SSE-3199 - Add domains to allowed email list

- .github/workflows/deploy-component.yml
- features/accessibilityFeatures/accessibility.feature
- features/base-template.feature
- features/documentation.feature
- features/error-pages.feature
- features/support/steps/shared-steps.ts
- package-lock.json
- package.json
https://govukverify.atlassian.net/browse/SSE-3181
Added accessibility tests for all product pages as defined [here](https://govukverify.atlassian.net/wiki/spaces/DFA/pages/3961946735/Product+site+pages)
Included rules wcag2.1 & 2.2
> SSE-3181 : Accessibility tests for product pages

- features/support/steps/contact-us-steps.ts
- features/support/steps/shared-steps.ts
https://govukverify.atlassian.net/browse/SSE-3245
> SSE-3245: Update Contact-us form submit details in automation test

- src/views/contact-us-confirm.njk
- src/views/register-confirm.njk
- src/views/register-error.njk
Add taxonomies to confirmation and error pages
> SSE-3152 - Add taxonomies to confirmation and error pages

- package-lock.json
SSE-3244 - Update packages for dependabot issue.
> SSE-3244 - Update packages for dependabot issue.

- resources/allowed-email-domains.txt
add missing email domains to the allow list to enable departments to onboard to one login
> SSE-3272: add email domains to the allow list

- package-lock.json
- src/controllers/prototype.ts
- src/routes/site.ts
- src/views/base-form.njk
- src/views/documentation-check-email.njk
- src/views/documentation-end-to-end-prototype.njk
- src/views/documentation-enter-email-address.njk
- src/views/macros/form.njk
- src/views/side-nav/documentation-side-nav.njk
SSE-3291 Create pages for Enter your work email address and One Login prototype
SSE-3292 Implement validate email logic
SSE-3293 Create banner: There is a problem
SSE-3295 Create page: Check your work email
> SSE-3291 SSE-3292 SSE-3293 SSE-3295 Frontend work for HTML Prototype Access

- features/accessibilityFeatures/accessibility.feature
- features/one-login-prototype.feature
story: https://govukverify.atlassian.net/browse/SSE-3315
Acceptance tests are to be added for the HTML prototype implemented functionality
> SSE-3315: Acceptance tests for HTML prototype

- infrastructure/frontend/frontend.template.yml
This reverts commit a6a0eed1c88a8ce1b2ab124fa1e161fe75c0ce8a.
> SSE-3312 Revert "SSE-3241: Added GA variables to frontend."

- infrastructure/frontend/frontend.template.yml
Coupled with https://github.com/govuk-one-login/onboarding-self-service-experience/pull/706
> WAF: Updated resource allocation.

- resources/allowed-email-domains.txt
> [!WARNING]
-   [ ] tests have been written to cover any new or updated functionality
-   [x] new configuration parameters have been deployed to all environments, see [configuration management](https://govukverify.atlassian.net/l/cp/N7q3Vh3r).
- …
> SSE-3323 Adding allowed domain: oisc.gov.uk

- src/routes/site.ts
- src/views/documentation-design-recommendations.njk
- src/views/documentation-migrating-users.njk
- src/views/side-nav/documentation-side-nav.njk
Content update - New page in the Design recommendations section
-   [X] this pull request meets the acceptance criteria of the ticket
-   [X] this branch is up-to-date with the main branch
-   [X] tests have been written to cover any new or updated functionality
Content Update
> SSE-3326 - New page in the Design recommendations section

- src/routes/site.ts
- src/views/documentation-design-recommendations.njk
- src/views/documentation-start-page.njk
- src/views/side-nav/documentation-side-nav.njk
Add new page in the Design recommendations section
> SSE-3362 Add new page in the Design recommendations section

- assets/javascripts/prevent-multiple-form-submission.js
- src/views/base-form.njk
- src/views/base.njk
Implement button disable feature  to prevent duplicate form submissions
> SSE-3334 Implement button disable feature 

- infrastructure/frontend/frontend.template.yml
> SSE-3434 enabled jira integration in prod

- test/controllers/register.spec.ts
Unit tests for register controller
> SSE-3400 - Unit tests for register controller

- .github/workflows/upload-frontend.yml
fixed test dockerfile path in  upload-frontend.yml
> [!WARNING]
- …
> SSE-3195 fixed test dockerfile path

- src/controllers/register.ts
- src/lib/jira/realJira/realJiraService.ts
- src/views/register.njk
- test/lib/jira/realJira/realJiraService.spec.ts
- test/lib/jira/testConstants.ts
- ui-automation-tests/acceptance-features/register.feature
- ui-automation-tests/support/steps/register-steps.ts
> [!WARNING]
-   [x] tests have been written to cover any new or …
> SSE-3425: Add migrate existing users question

- src/views/support.njk
> [!WARNING]
-   [x] tests have been written to cover any new or …
> SSE-3440: Update the hours for user support on product pages

- .github/workflows/upload-frontend.yml
> SSE-3444 enabled build secure-pipeline tests

- .github/workflows/upload-frontend.yml
Reverts govuk-one-login/onboarding-product-page#417
> Revert "SSE-3444 enabled build secure-pipeline tests"

- package-lock.json
- package.json
- resources/allowed-email-domains.txt
- ui-automation-tests/package.json
- ui-automation-tests/reports/.gitignore
- ui-automation-tests/support/steps/base-template-steps.ts
- ui-automation-tests/support/steps/documentation-steps.ts
- ui-automation-tests/support/steps/register-steps.ts
- ui-automation-tests/support/steps/shared-functions.ts
- ui-automation-tests/support/steps/shared-steps.ts
- ui-automation-tests/support/steps/support-steps.ts
- ui-automation-tests/support/steps/user-journeys-steps.ts
> SSE-3454 Adding activetravelengland.gov.uk

- src/views/documentation-design-recommendations.njk
- src/views/documentation-migrating-users.njk
- src/views/side-nav/documentation-side-nav.njk
[AP-296](https://govukverify.atlassian.net/browse/AP-296)
Correct all references to `GOV.UK Login` to read `GOV.UK One Login` on https://www.sign-in.service.gov.uk/documentation/design-recommendations/migrating-users
> [!WARNING]
-   [x] these …
> AP-296 - Correct "GOV.UK Login" to read "GOV.UK One Login" - minor change to product site

- resources/allowed-email-domains.txt
[AP-303](https://govukverify.atlassian.net/browse/AP-303)
> [!WARNING] …
> AP-303 add businessandtrade.gov.uk to the allow list of email domains

- src/routes/site.ts
- src/views/documentation-how-to-talk-about.njk
- src/views/side-nav/documentation-side-nav.njk
[AP-311](https://govukverify.atlassian.net/browse/AP-311)
> [!WARNING] …
> AP-311 - Update product site with how to talk about GOV.UK One Login guidance

- package-lock.json
- resources/allowed-email-domains.txt
> Add service.education.gov.uk to allowed email domains

- src/routes/site.ts
- src/views/documentation-prepare-move-content.njk
- src/views/documentation-prepare-to-move.njk
- src/views/side-nav/documentation-side-nav.njk
[AP-348](https://govukverify.atlassian.net/browse/AP-348)
> [!WARNING] …
> AP-348 Publish 'Prepare your users to move to GOV.UK One Login' on product site

- src/views/roadmap.njk
[AP-382](https://govukverify.atlassian.net/browse/AP-382)
> [!WARNING] …
> AP-382 - november 2024 roadmap update

- package-lock.json
> BAU: Bump cross spawn depedency to 7.0.6

- src/routes/site.ts
- src/views/documentation-migrating-sign-in-pattern.njk
- src/views/side-nav/documentation-side-nav.njk
[AP-385](https://govukverify.atlassian.net/browse/AP-385)
> [!WARNING] …
> AP-385 add new guidance page - Moving to GOV.UK One Login if you need to sign in your users

- resources/allowed-email-domains.txt
> ATO-1340/ATO-1341: Add new domains

- src/views/about/evidence-types.njk
- src/views/documentation-identity-journeys.njk
- src/views/documentation-migrating-users.njk
- src/views/documentation-user-journeys.njk
- src/views/roadmap.njk
> Content changes for 2024 week 4

- src/routes/site.ts
- src/views/documentation-business-users.njk
- src/views/documentation-design-recommendations.njk
- src/views/documentation-user-journeys.njk
- src/views/side-nav/documentation-side-nav.njk
> Content changes to the product pages for week 5

- .github/workflows/test.yml
Sonarcloud action is being deprecated
> [!WARNING]
-   [ ] tests …
> ATO-1448: Migrate sonarcloud action to sonarqube

- src/routes/site.ts
- src/views/about.njk
- src/views/documentation-barriers-prove-identity.njk
- src/views/side-nav/documentation-side-nav.njk
- https://govukverify.atlassian.net/issues/AP-417  Why is One Login right for RPs? (for service teams + SMTs) - about page
- https://govukverify.atlassian.net/issues/AP-389 Service design recommendation: RPs should always think about how to support users that OL cannot serve
> [!WARNING] …
> Content 2025 week7 [AP-417 AP389]

- .github/CODEOWNERS
> BAU: Allow adoption architects to make content changes to product-pages

- .github/workflows/deploy-branch.yml
> ATO-1509: replace forward slashes in image tag name

- resources/allowed-email-domains.txt
https://govukverify.atlassian.net/browse/AP-437
> [!WARNING]
-   [ …
> AP-437 -test new code owner powers by removing rogue domain

- infrastructure/frontend/frontend.template.yml
Add tags so that FMS can find the resources to add policies to
> [!WARNING] …
> ATO-1532: Add FMS tags

- infrastructure/frontend/frontend.template.yml
This should be picked up by FMS and it will deploy its own Web ACL
> [!WARNING] …
> ATO-1532: Disassociate Web ACL in dev

- infrastructure/frontend/frontend.template.yml
> BAU: Disassociate waf in build

- package-lock.json
- package.json
Runs `npm update tar-fs 3.0.8` to resolve vulnerability[1] and also pins puppeteer
[1]- https://github.com/govuk-one-login/onboarding-product-page/security/dependabot/78
> [!WARNING]
-   [ ] these changes are backwards compatible (no breaking …
> BAU: Update tar-fs and pin puppeteer

- infrastructure/frontend/frontend.template.yml
> BAU: Disassociate waf in int

- infrastructure/frontend/frontend.template.yml
> ATO-1532: Disassociate waf in prod

- resources/allowed-email-domains.txt
[AP-523](https://govukverify.atlassian.net/browse/AP-523)
> [!WARNING] …
> AP-523 - add nda.gov.uk to the email domain allow list

- infrastructure/frontend/frontend.template.yml
- package-lock.json
- resources/allowed-email-domains.txt
[AP-553](https://govukverify.atlassian.net/browse/AP-553)
> [!WARNING]
- all methods signatures and return values are the same
- any replaced methods are marked as `@deprecated`
- add `dsit.gov.uk`
- remove rogue @ symbols in domain names
- remove duplicate domains
[AP-553]: https://govukverify.atlassian.net/browse/AP-553?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2 …
> AP-553 - Add dsit.gov.uk to the product-page allow list to enable the team for fill in registation form

- src/views/about.njk
- src/views/getting-started.njk
- src/views/roadmap.njk
[AP-531](https://govukverify.atlassian.net/browse/AP-531)
> [!WARNING]
- all methods signatures and return values are the same
- any replaced methods are marked as `@deprecated`
[ _please list the changes this pull request is making_ ]
- add wallet content to `about.njk`
- add wallet content to `getting-started.njk`
- update roadmap for june 2025 `roadmap.njk` …
> AP-531 - Product site updates (roadmap update and new wallet content)

- .github/dependabot.yml
- Dockerfile
- package-lock.json
- all methods signatures and return values are the same
- any replaced methods are marked as `@deprecated`
- Changes the build process to omit dev dependencies once the application is built 
- Uses npm ci instead of npm install in the docker file to ensure build is determined by `package-lock.json`
- Runs npm audit fix to update transitive dependencies 
- Updates dependabot.yml to ensure it picks up node version bumps that are not major
- Deployed to dev and everything looks fine
> ATO-1954: add docker to dependabot
